version: "3.8"
services:
  eos-develop-env:
    build:
      context: .
      dockerfile: Dockerfile
    image: eos-develop-env:latest
    hostname: eos-develop-env
    network_mode: bridge
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./development:/home/eosio/development
      - ./node:/home/eosio/node 
    container_name: eos-develop-env

