version: "3.8"
services:
  dante:
    build:
      context: .
      dockerfile: Dockerfile
    image: dante:latest
    hostname: dante
    network_mode: bridge
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/etc/dante
    tmpfs:
      - /run
    ports:
      - "1080:1080"
    container_name: dante
