version: "3.8"
services:
  dante:
    build:
      context: .
      dockerfile: Dockerfile
    image: dante:latest
    ports:
      - "1080:1080"
    volumes:
      - ./data:/etc/dante
    tmpfs:
      - /run
    restart: unless-stopped
    container_name: dante
